### ISSUE TITLE
Cannot convert value "UTF8NoBOM"

### ISSUE THREAD

**Issue by ibeketov** [ajoberstar/ArchitectureDecisionRecords#1]
```
Get-Content : Cannot bind parameter 'Encoding'. Cannot convert value "UTF8NoBOM" to type "Microsoft.PowerShell.Commands.FileSystemCmdletProviderEncoding". Error: "Unable to match the identifier
name UTF8NoBOM to a valid enumerator name. Specify one of the following enumerator names and try again:
Unknown, String, Unicode, Byte, BigEndianUnicode, UTF8, UTF7, UTF32, Ascii, Default, Oem, BigEndianUTF32"
At C:\Users\[USER_NAME]\Personal Data\WindowsPowerShell\Modules\ArchitectureDecisionRecords\0.1.1\ArchitectureDecisionRecords.psm1:69 char:45
+   Get-Content -Path $TemplateFile -Encoding UTF8NoBOM
+                                             ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Content], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.GetContentCommand
```

**Comment by ajoberstar** [comment]
Good catch. I think I'll probably switch to ASCII, since UTF8NoBom is only in Powershell core.

**Comment by ibeketov** [comment]
Hm, strange I’ve run it at Win10 Pro so I supposed that it should be compatible. I’ve changed it to UTF8 and it seems that it works fine.

**Comment by ajoberstar** [comment]
Win 10 comes with PowerShell 5.1 (which is the "desktop" variant). You can separately install PowerShell Core (which is the cross-platform version). In 5.1, the UTF8 encoding results in a BOM at the start of the file. In Core, UTF8 seems to create a BOM-less file, but UTF8NoBOM is the more explicit way to do this. 

Since I want this utility to work with ADRs created on Linux (with the bash tooling), where the default is BOM-less UTF8, I think the two options are:

- Read/Write files with Get-Content/Set-Content ASCII on PowerShell 5.1
- Read/Write files with .NET methods as BOM-less UTF8 on all PowerShell versions

Second option is the most compatible though, in case people use non-ASCII characters in the files.
